import { t, type T } from "@/lib/i18n";

export const storefrontCopy = {
  title: t("Storefront profile", "Profil sklepu", "Shop-Profil", "Hồ sơ gian hàng"),
  intro: t(
    "Prepare private profile changes, submit them for review, and control an approved storefront separately.",
    "Przygotuj prywatne zmiany profilu, wyślij je do weryfikacji i oddzielnie zarządzaj zatwierdzonym sklepem.",
    "Bereite private Profiländerungen vor, reiche sie zur Prüfung ein und steuere den freigegebenen Shop separat.",
    "Chuẩn bị thay đổi hồ sơ riêng tư, gửi để xét duyệt và quản lý riêng gian hàng đã được phê duyệt.",
  ),
  loading: t("Loading…", "Ładowanie…", "Wird geladen…", "Đang tải…"),
  loadFailed: t(
    "Seller profile could not be loaded.",
    "Nie udało się wczytać profilu sprzedawcy.",
    "Das Verkäuferprofil konnte nicht geladen werden.",
    "Không thể tải hồ sơ người bán.",
  ),
  approvalTitle: t("Storefront status", "Status sklepu", "Shop-Status", "Trạng thái gian hàng"),
  notApproved: t("Not approved", "Niezatwierdzony", "Nicht freigegeben", "Chưa được phê duyệt"),
  approvedDisabled: t(
    "Approved, storefront disabled",
    "Zatwierdzony, sklep wyłączony",
    "Freigegeben, Shop deaktiviert",
    "Đã phê duyệt, gian hàng đang tắt",
  ),
  approvedEnabled: t(
    "Approved and visible",
    "Zatwierdzony i widoczny",
    "Freigegeben und sichtbar",
    "Đã phê duyệt và hiển thị",
  ),
  notApprovedHelp: t(
    "Submit the profile and wait for administrator approval before enabling the storefront.",
    "Wyślij profil i poczekaj na zatwierdzenie administratora, zanim włączysz sklep.",
    "Reiche das Profil ein und warte auf die Freigabe, bevor du den Shop aktivierst.",
    "Gửi hồ sơ và chờ quản trị viên phê duyệt trước khi bật gian hàng.",
  ),
  storefrontEnabledHelp: t(
    "Buyers can see the currently approved profile.",
    "Kupujący widzą obecnie zatwierdzony profil.",
    "Käufer sehen das aktuell freigegebene Profil.",
    "Người mua có thể xem hồ sơ hiện đã được phê duyệt.",
  ),
  storefrontDisabledHelp: t(
    "The approved profile is retained but hidden from buyers.",
    "Zatwierdzony profil jest zachowany, ale ukryty przed kupującymi.",
    "Das freigegebene Profil bleibt erhalten, ist aber für Käufer verborgen.",
    "Hồ sơ đã phê duyệt được giữ lại nhưng ẩn với người mua.",
  ),
  enableStorefront: t("Enable storefront", "Włącz sklep", "Shop aktivieren", "Bật gian hàng"),
  disableStorefront: t("Disable storefront", "Wyłącz sklep", "Shop deaktivieren", "Tắt gian hàng"),
  updatingStorefront: t("Updating…", "Aktualizowanie…", "Wird aktualisiert…", "Đang cập nhật…"),
  reviewTitle: t(
    "Latest review",
    "Ostatnia weryfikacja",
    "Letzte Prüfung",
    "Lần xét duyệt gần nhất",
  ),
  noSubmission: t(
    "This profile has not been submitted for review yet.",
    "Ten profil nie został jeszcze wysłany do weryfikacji.",
    "Dieses Profil wurde noch nicht zur Prüfung eingereicht.",
    "Hồ sơ này chưa được gửi để xét duyệt.",
  ),
  initialSubmission: t("Initial profile", "Profil początkowy", "Erstprofil", "Hồ sơ ban đầu"),
  updateSubmission: t(
    "Profile update",
    "Aktualizacja profilu",
    "Profilaktualisierung",
    "Cập nhật hồ sơ",
  ),
  pending: t(
    "Pending review",
    "Oczekuje na weryfikację",
    "Prüfung ausstehend",
    "Đang chờ xét duyệt",
  ),
  changesRequested: t(
    "Changes requested",
    "Wymagane zmiany",
    "Änderungen angefordert",
    "Yêu cầu chỉnh sửa",
  ),
  approved: t("Approved", "Zatwierdzony", "Freigegeben", "Đã phê duyệt"),
  rejected: t("Rejected", "Odrzucony", "Abgelehnt", "Bị từ chối"),
  withdrawn: t("Withdrawn", "Wycofany", "Zurückgezogen", "Đã rút lại"),
  submittedAt: t("Submitted", "Wysłano", "Eingereicht", "Đã gửi"),
  decidedAt: t("Decided", "Decyzja", "Entschieden", "Đã quyết định"),
  feedbackTitle: t(
    "Administrator feedback",
    "Uwagi administratora",
    "Rückmeldung der Administration",
    "Phản hồi của quản trị viên",
  ),
  approvedProfileTitle: t(
    "Approved public profile",
    "Zatwierdzony profil publiczny",
    "Freigegebenes öffentliches Profil",
    "Hồ sơ công khai đã phê duyệt",
  ),
  approvedProfileHelp: t(
    "This immutable revision remains public until a newer update is approved.",
    "Ta niezmienna wersja pozostaje publiczna do czasu zatwierdzenia nowszej aktualizacji.",
    "Diese unveränderliche Version bleibt öffentlich, bis eine neuere Aktualisierung freigegeben wird.",
    "Phiên bản bất biến này vẫn công khai cho đến khi bản cập nhật mới hơn được phê duyệt.",
  ),
  privateDraftTitle: t(
    "Unpublished profile changes",
    "Nieopublikowane zmiany profilu",
    "Unveröffentlichte Profiländerungen",
    "Thay đổi hồ sơ chưa công bố",
  ),
  privateDraftHelp: t(
    "Save changes privately, then submit the saved revision for review.",
    "Zapisz zmiany prywatnie, a następnie wyślij zapisaną wersję do weryfikacji.",
    "Speichere Änderungen privat und reiche danach die gespeicherte Version zur Prüfung ein.",
    "Lưu thay đổi riêng tư, sau đó gửi phiên bản đã lưu để xét duyệt.",
  ),
  pendingReadOnly: t(
    "The submitted revision is under review. Withdraw it before making more profile changes.",
    "Wysłana wersja jest w trakcie weryfikacji. Wycofaj ją przed wprowadzeniem kolejnych zmian.",
    "Die eingereichte Version wird geprüft. Ziehe sie zurück, bevor du weitere Änderungen vornimmst.",
    "Phiên bản đã gửi đang được xét duyệt. Hãy rút lại trước khi chỉnh sửa thêm.",
  ),
  businessName: t("Business name", "Nazwa firmy", "Firmenname", "Tên doanh nghiệp"),
  slug: t(
    "URL slug (a-z, 0-9, -)",
    "Adres URL (a-z, 0-9, -)",
    "URL-Kürzel (a-z, 0-9, -)",
    "Đường dẫn URL (a-z, 0-9, -)",
  ),
  businessCategory: t(
    "Business category",
    "Kategoria firmy",
    "Unternehmenskategorie",
    "Danh mục doanh nghiệp",
  ),
  fashion: t("Fashion", "Moda", "Mode", "Thời trang"),
  city: t("City", "Miasto", "Stadt", "Thành phố"),
  country: t("Country", "Kraj", "Land", "Quốc gia"),
  whatsapp: t("WhatsApp", "WhatsApp", "WhatsApp", "WhatsApp"),
  contactEmail: t("Contact email", "E-mail kontaktowy", "Kontakt-E-Mail", "Email liên hệ"),
  establishedYear: t("Established year", "Rok założenia", "Gründungsjahr", "Năm thành lập"),
  about: t("About", "O firmie", "Über uns", "Giới thiệu"),
  saveDraft: t(
    "Save profile draft",
    "Zapisz szkic profilu",
    "Profilentwurf speichern",
    "Lưu bản nháp hồ sơ",
  ),
  saving: t("Saving…", "Zapisywanie…", "Wird gespeichert…", "Đang lưu…"),
  submitReview: t(
    "Submit profile for review",
    "Wyślij profil do weryfikacji",
    "Profil zur Prüfung einreichen",
    "Gửi hồ sơ để xét duyệt",
  ),
  submitting: t("Submitting…", "Wysyłanie…", "Wird eingereicht…", "Đang gửi…"),
  withdraw: t("Withdraw submission", "Wycofaj zgłoszenie", "Einreichung zurückziehen", "Rút hồ sơ"),
  withdrawing: t("Withdrawing…", "Wycofywanie…", "Wird zurückgezogen…", "Đang rút…"),
  saveBeforeSubmit: t(
    "Save the current changes before submitting them for review.",
    "Zapisz bieżące zmiany przed wysłaniem ich do weryfikacji.",
    "Speichere die aktuellen Änderungen, bevor du sie zur Prüfung einreichst.",
    "Lưu các thay đổi hiện tại trước khi gửi để xét duyệt.",
  ),
  draftSaved: t(
    "Profile draft saved.",
    "Szkic profilu zapisany.",
    "Profilentwurf gespeichert.",
    "Đã lưu bản nháp hồ sơ.",
  ),
  logoSaved: t("Logo saved.", "Logo zapisane.", "Logo gespeichert.", "Đã lưu logo."),
  coverSaved: t(
    "Cover image saved.",
    "Zdjęcie okładki zapisane.",
    "Titelbild gespeichert.",
    "Đã lưu ảnh bìa.",
  ),
  logoRemoved: t("Logo removed.", "Logo usunięte.", "Logo entfernt.", "Đã xóa logo."),
  coverRemoved: t(
    "Cover image removed.",
    "Zdjęcie okładki usunięte.",
    "Titelbild entfernt.",
    "Đã xóa ảnh bìa.",
  ),
  submittedSuccess: t(
    "Profile submitted for review.",
    "Profil wysłany do weryfikacji.",
    "Profil zur Prüfung eingereicht.",
    "Đã gửi hồ sơ để xét duyệt.",
  ),
  withdrawnSuccess: t(
    "Submission withdrawn.",
    "Zgłoszenie wycofane.",
    "Einreichung zurückgezogen.",
    "Đã rút hồ sơ.",
  ),
  storefrontEnabledSuccess: t(
    "Storefront enabled.",
    "Sklep włączony.",
    "Shop aktiviert.",
    "Đã bật gian hàng.",
  ),
  storefrontDisabledSuccess: t(
    "Storefront disabled.",
    "Sklep wyłączony.",
    "Shop deaktiviert.",
    "Đã tắt gian hàng.",
  ),
  revisionConflict: t(
    "This profile changed elsewhere. The latest revision was loaded while your unsaved fields were preserved.",
    "Ten profil został zmieniony gdzie indziej. Wczytano najnowszą wersję, zachowując niezapisane pola.",
    "Dieses Profil wurde an anderer Stelle geändert. Die neueste Version wurde geladen, nicht gespeicherte Felder blieben erhalten.",
    "Hồ sơ đã được thay đổi ở nơi khác. Phiên bản mới nhất đã được tải và các trường chưa lưu vẫn được giữ lại.",
  ),
  invalid: t(
    "Check the profile fields and try again.",
    "Sprawdź pola profilu i spróbuj ponownie.",
    "Prüfe die Profilfelder und versuche es erneut.",
    "Kiểm tra các trường hồ sơ và thử lại.",
  ),
  actionConflict: t(
    "This request conflicts with an earlier profile action. Refresh and try again.",
    "To żądanie koliduje z wcześniejszą operacją na profilu. Odśwież stronę i spróbuj ponownie.",
    "Diese Anfrage steht im Konflikt mit einer früheren Profilaktion. Aktualisiere die Seite und versuche es erneut.",
    "Yêu cầu này xung đột với thao tác hồ sơ trước đó. Hãy tải lại và thử lại.",
  ),
  slugConflict: t(
    "This storefront address is already in use. Choose another URL slug.",
    "Ten adres sklepu jest już używany. Wybierz inny adres URL.",
    "Diese Shop-Adresse wird bereits verwendet. Wähle ein anderes URL-Kürzel.",
    "Địa chỉ gian hàng này đã được sử dụng. Hãy chọn đường dẫn URL khác.",
  ),
  approvalRequired: t(
    "The profile must be approved before the storefront can be enabled.",
    "Profil musi zostać zatwierdzony, zanim będzie można włączyć sklep.",
    "Das Profil muss freigegeben sein, bevor der Shop aktiviert werden kann.",
    "Hồ sơ phải được phê duyệt trước khi có thể bật gian hàng.",
  ),
  notFound: t(
    "Seller profile could not be found.",
    "Nie znaleziono profilu sprzedawcy.",
    "Das Verkäuferprofil wurde nicht gefunden.",
    "Không tìm thấy hồ sơ người bán.",
  ),
  imageNotReady: t(
    "The selected logo or cover image is not ready.",
    "Wybrane logo lub zdjęcie okładki nie jest gotowe.",
    "Das ausgewählte Logo oder Titelbild ist noch nicht bereit.",
    "Logo hoặc ảnh bìa đã chọn chưa sẵn sàng.",
  ),
  unavailable: t(
    "Seller profile is temporarily unavailable.",
    "Profil sprzedawcy jest tymczasowo niedostępny.",
    "Das Verkäuferprofil ist vorübergehend nicht verfügbar.",
    "Hồ sơ người bán tạm thời không khả dụng.",
  ),
} satisfies Record<string, T>;

export const sellerProfileMediaCopy = {
  logo: t("Logo", "Logo", "Logo", "Logo"),
  cover: t("Cover image", "Zdjęcie okładki", "Titelbild", "Ảnh bìa"),
  privateHelp: t(
    "Private until an administrator approves this profile revision.",
    "Prywatne do czasu zatwierdzenia tej wersji profilu przez administratora.",
    "Privat, bis diese Profilversion freigegeben wird.",
    "Riêng tư cho đến khi quản trị viên phê duyệt phiên bản hồ sơ này.",
  ),
  chooseFile: t(
    "Choose a non-empty JPEG, PNG, or WebP image no larger than 20 MB.",
    "Wybierz niepusty obraz JPEG, PNG lub WebP o rozmiarze do 20 MB.",
    "Wähle ein nicht leeres JPEG-, PNG- oder WebP-Bild bis 20 MB.",
    "Chọn ảnh JPEG, PNG hoặc WebP không rỗng, tối đa 20 MB.",
  ),
  working: t("Working…", "Przetwarzanie…", "Wird verarbeitet…", "Đang xử lý…"),
  upload: t("Upload", "Prześlij", "Hochladen", "Tải lên"),
  replace: t("Replace", "Zastąp", "Ersetzen", "Thay thế"),
  remove: t("Remove", "Usuń", "Entfernen", "Xóa"),
  loading: t("Loading image…", "Ładowanie obrazu…", "Bild wird geladen…", "Đang tải ảnh…"),
  placeholder: t("Image placeholder", "Miejsce na obraz", "Bildplatzhalter", "Vị trí ảnh"),
  invalid: t(
    "The selected file is not a valid supported image.",
    "Wybrany plik nie jest prawidłowym obsługiwanym obrazem.",
    "Die ausgewählte Datei ist kein gültiges unterstütztes Bild.",
    "Tệp đã chọn không phải ảnh được hỗ trợ hợp lệ.",
  ),
  cleanup: t(
    "The profile was updated, but old image cleanup must be retried.",
    "Profil zaktualizowano, ale usuwanie starego obrazu trzeba ponowić.",
    "Das Profil wurde aktualisiert, aber die Bereinigung des alten Bildes muss wiederholt werden.",
    "Hồ sơ đã được cập nhật nhưng cần thử lại việc dọn ảnh cũ.",
  ),
  notReady: t(
    "The image is not ready. Select the file again or retry shortly.",
    "Obraz nie jest gotowy. Wybierz plik ponownie lub spróbuj za chwilę.",
    "Das Bild ist noch nicht bereit. Wähle die Datei erneut oder versuche es später.",
    "Ảnh chưa sẵn sàng. Chọn lại tệp hoặc thử lại sau.",
  ),
  unavailable: t(
    "The seller profile image is temporarily unavailable.",
    "Obraz profilu sprzedawcy jest tymczasowo niedostępny.",
    "Das Verkäuferprofilbild ist vorübergehend nicht verfügbar.",
    "Ảnh hồ sơ người bán tạm thời không khả dụng.",
  ),
} satisfies Record<string, T>;
