/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSellerSlugRouteImport } from './routes/s.$sellerSlug'
import { Route as PProductIdRouteImport } from './routes/p.$productId'
import { Route as DemoMarketplaceRouteImport } from './routes/demo.marketplace'
import { Route as DemoKesarTextilesRouteImport } from './routes/demo.kesar-textiles'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as V1AdminClassifierImportsRouteImport } from './routes/v1.admin.classifier-imports'
import { Route as V1AdminClassifierImportDestinationRouteImport } from './routes/v1.admin.classifier-import-destination'
import { Route as V1AdminClassifierBatchesRouteImport } from './routes/v1.admin.classifier-batches'
import { Route as AuthenticatedSellerStorefrontRouteImport } from './routes/_authenticated/seller.storefront'
import { Route as AuthenticatedSellerProductsRouteImport } from './routes/_authenticated/seller.products'
import { Route as AuthenticatedSellerLeadsRouteImport } from './routes/_authenticated/seller.leads'
import { Route as AuthenticatedSellerClassifierBatchesRouteImport } from './routes/_authenticated/seller.classifier-batches'
import { Route as AuthenticatedAdminProductDraftsRouteImport } from './routes/_authenticated/admin.product-drafts'
import { Route as AuthenticatedAdminClassifierImportsRouteImport } from './routes/_authenticated/admin.classifier-imports'
import { Route as V1AdminClassifierImportsImportIdRouteImport } from './routes/v1.admin.classifier-imports.$importId'
import { Route as AuthenticatedSellerProductsNewRouteImport } from './routes/_authenticated/seller.products_.new'
import { Route as AuthenticatedSellerProductsIdRouteImport } from './routes/_authenticated/seller.products_.$id'
import { Route as AuthenticatedSellerClassifierBatchesNewRouteImport } from './routes/_authenticated/seller.classifier-batches_.new'
import { Route as AuthenticatedAdminProductDraftsProductDraftIdRouteImport } from './routes/_authenticated/admin.product-drafts_.$productDraftId'
import { Route as AuthenticatedAdminClassifierUploadsNewRouteImport } from './routes/_authenticated/admin.classifier-uploads_.new'
import { Route as AuthenticatedAdminClassifierUploadsWorkflowIdRouteImport } from './routes/_authenticated/admin.classifier-uploads_.$workflowId'
import { Route as AuthenticatedAdminClassifierImportsImportIdRouteImport } from './routes/_authenticated/admin.classifier-imports_.$importId'
import { Route as V1AdminClassifierImportsImportIdRetryRouteImport } from './routes/v1.admin.classifier-imports.$importId.retry'
import { Route as V1AdminClassifierImportsImportIdReconcileRouteImport } from './routes/v1.admin.classifier-imports.$importId.reconcile'
import { Route as V1AdminClassifierImportsImportIdDispatchRouteImport } from './routes/v1.admin.classifier-imports.$importId.dispatch'
import { Route as AuthenticatedSellerClassifierBatchesWorkflowIdUploadRouteImport } from './routes/_authenticated/seller.classifier-batches_.$workflowId.upload'
import { Route as AuthenticatedSellerClassifierBatchesWorkflowIdReviewRouteImport } from './routes/_authenticated/seller.classifier-batches_.$workflowId.review'
import { Route as AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRouteImport } from './routes/_authenticated/seller.classifier-batches_.$workflowId.processing'
import { Route as AuthenticatedSellerClassifierBatchesWorkflowIdImportRouteImport } from './routes/_authenticated/seller.classifier-batches_.$workflowId.import'
import { Route as AuthenticatedAdminProductDraftsProductDraftIdFactsRouteImport } from './routes/_authenticated/admin.product-drafts_.$productDraftId.facts'
import { Route as V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRouteImport } from './routes/v1.seller.classifier-batches.$workflowId.images.$imageId.thumbnail'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSellerSlugRoute = SSellerSlugRouteImport.update({
  id: '/s/$sellerSlug',
  path: '/s/$sellerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PProductIdRoute = PProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMarketplaceRoute = DemoMarketplaceRouteImport.update({
  id: '/demo/marketplace',
  path: '/demo/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKesarTextilesRoute = DemoKesarTextilesRouteImport.update({
  id: '/demo/kesar-textiles',
  path: '/demo/kesar-textiles',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const V1AdminClassifierImportsRoute =
  V1AdminClassifierImportsRouteImport.update({
    id: '/v1/admin/classifier-imports',
    path: '/v1/admin/classifier-imports',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminClassifierImportDestinationRoute =
  V1AdminClassifierImportDestinationRouteImport.update({
    id: '/v1/admin/classifier-import-destination',
    path: '/v1/admin/classifier-import-destination',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminClassifierBatchesRoute =
  V1AdminClassifierBatchesRouteImport.update({
    id: '/v1/admin/classifier-batches',
    path: '/v1/admin/classifier-batches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSellerStorefrontRoute =
  AuthenticatedSellerStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsRoute =
  AuthenticatedSellerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerLeadsRoute =
  AuthenticatedSellerLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesRoute =
  AuthenticatedSellerClassifierBatchesRouteImport.update({
    id: '/classifier-batches',
    path: '/classifier-batches',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedAdminProductDraftsRoute =
  AuthenticatedAdminProductDraftsRouteImport.update({
    id: '/admin/product-drafts',
    path: '/admin/product-drafts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassifierImportsRoute =
  AuthenticatedAdminClassifierImportsRouteImport.update({
    id: '/admin/classifier-imports',
    path: '/admin/classifier-imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const V1AdminClassifierImportsImportIdRoute =
  V1AdminClassifierImportsImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => V1AdminClassifierImportsRoute,
  } as any)
const AuthenticatedSellerProductsNewRoute =
  AuthenticatedSellerProductsNewRouteImport.update({
    id: '/products_/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsIdRoute =
  AuthenticatedSellerProductsIdRouteImport.update({
    id: '/products_/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesNewRoute =
  AuthenticatedSellerClassifierBatchesNewRouteImport.update({
    id: '/classifier-batches_/new',
    path: '/classifier-batches/new',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedAdminProductDraftsProductDraftIdRoute =
  AuthenticatedAdminProductDraftsProductDraftIdRouteImport.update({
    id: '/admin/product-drafts_/$productDraftId',
    path: '/admin/product-drafts/$productDraftId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassifierUploadsNewRoute =
  AuthenticatedAdminClassifierUploadsNewRouteImport.update({
    id: '/admin/classifier-uploads_/new',
    path: '/admin/classifier-uploads/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassifierUploadsWorkflowIdRoute =
  AuthenticatedAdminClassifierUploadsWorkflowIdRouteImport.update({
    id: '/admin/classifier-uploads_/$workflowId',
    path: '/admin/classifier-uploads/$workflowId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassifierImportsImportIdRoute =
  AuthenticatedAdminClassifierImportsImportIdRouteImport.update({
    id: '/admin/classifier-imports_/$importId',
    path: '/admin/classifier-imports/$importId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const V1AdminClassifierImportsImportIdRetryRoute =
  V1AdminClassifierImportsImportIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => V1AdminClassifierImportsImportIdRoute,
  } as any)
const V1AdminClassifierImportsImportIdReconcileRoute =
  V1AdminClassifierImportsImportIdReconcileRouteImport.update({
    id: '/reconcile',
    path: '/reconcile',
    getParentRoute: () => V1AdminClassifierImportsImportIdRoute,
  } as any)
const V1AdminClassifierImportsImportIdDispatchRoute =
  V1AdminClassifierImportsImportIdDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => V1AdminClassifierImportsImportIdRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute =
  AuthenticatedSellerClassifierBatchesWorkflowIdUploadRouteImport.update({
    id: '/classifier-batches_/$workflowId/upload',
    path: '/classifier-batches/$workflowId/upload',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute =
  AuthenticatedSellerClassifierBatchesWorkflowIdReviewRouteImport.update({
    id: '/classifier-batches_/$workflowId/review',
    path: '/classifier-batches/$workflowId/review',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute =
  AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRouteImport.update({
    id: '/classifier-batches_/$workflowId/processing',
    path: '/classifier-batches/$workflowId/processing',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute =
  AuthenticatedSellerClassifierBatchesWorkflowIdImportRouteImport.update({
    id: '/classifier-batches_/$workflowId/import',
    path: '/classifier-batches/$workflowId/import',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedAdminProductDraftsProductDraftIdFactsRoute =
  AuthenticatedAdminProductDraftsProductDraftIdFactsRouteImport.update({
    id: '/facts',
    path: '/facts',
    getParentRoute: () => AuthenticatedAdminProductDraftsProductDraftIdRoute,
  } as any)
const V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute =
  V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRouteImport.update({
    id: '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail',
    path: '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/c/$category': typeof CCategoryRoute
  '/demo/kesar-textiles': typeof DemoKesarTextilesRoute
  '/demo/marketplace': typeof DemoMarketplaceRoute
  '/p/$productId': typeof PProductIdRoute
  '/s/$sellerSlug': typeof SSellerSlugRoute
  '/admin/classifier-imports': typeof AuthenticatedAdminClassifierImportsRoute
  '/admin/product-drafts': typeof AuthenticatedAdminProductDraftsRoute
  '/seller/classifier-batches': typeof AuthenticatedSellerClassifierBatchesRoute
  '/seller/leads': typeof AuthenticatedSellerLeadsRoute
  '/seller/products': typeof AuthenticatedSellerProductsRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/v1/admin/classifier-batches': typeof V1AdminClassifierBatchesRoute
  '/v1/admin/classifier-import-destination': typeof V1AdminClassifierImportDestinationRoute
  '/v1/admin/classifier-imports': typeof V1AdminClassifierImportsRouteWithChildren
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/admin/classifier-imports/$importId': typeof AuthenticatedAdminClassifierImportsImportIdRoute
  '/admin/classifier-uploads/$workflowId': typeof AuthenticatedAdminClassifierUploadsWorkflowIdRoute
  '/admin/classifier-uploads/new': typeof AuthenticatedAdminClassifierUploadsNewRoute
  '/admin/product-drafts/$productDraftId': typeof AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren
  '/seller/classifier-batches/new': typeof AuthenticatedSellerClassifierBatchesNewRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/v1/admin/classifier-imports/$importId': typeof V1AdminClassifierImportsImportIdRouteWithChildren
  '/admin/product-drafts/$productDraftId/facts': typeof AuthenticatedAdminProductDraftsProductDraftIdFactsRoute
  '/seller/classifier-batches/$workflowId/import': typeof AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute
  '/seller/classifier-batches/$workflowId/processing': typeof AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute
  '/seller/classifier-batches/$workflowId/review': typeof AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute
  '/seller/classifier-batches/$workflowId/upload': typeof AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute
  '/v1/admin/classifier-imports/$importId/dispatch': typeof V1AdminClassifierImportsImportIdDispatchRoute
  '/v1/admin/classifier-imports/$importId/reconcile': typeof V1AdminClassifierImportsImportIdReconcileRoute
  '/v1/admin/classifier-imports/$importId/retry': typeof V1AdminClassifierImportsImportIdRetryRoute
  '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail': typeof V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/$category': typeof CCategoryRoute
  '/demo/kesar-textiles': typeof DemoKesarTextilesRoute
  '/demo/marketplace': typeof DemoMarketplaceRoute
  '/p/$productId': typeof PProductIdRoute
  '/s/$sellerSlug': typeof SSellerSlugRoute
  '/admin/classifier-imports': typeof AuthenticatedAdminClassifierImportsRoute
  '/admin/product-drafts': typeof AuthenticatedAdminProductDraftsRoute
  '/seller/classifier-batches': typeof AuthenticatedSellerClassifierBatchesRoute
  '/seller/leads': typeof AuthenticatedSellerLeadsRoute
  '/seller/products': typeof AuthenticatedSellerProductsRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/v1/admin/classifier-batches': typeof V1AdminClassifierBatchesRoute
  '/v1/admin/classifier-import-destination': typeof V1AdminClassifierImportDestinationRoute
  '/v1/admin/classifier-imports': typeof V1AdminClassifierImportsRouteWithChildren
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/admin/classifier-imports/$importId': typeof AuthenticatedAdminClassifierImportsImportIdRoute
  '/admin/classifier-uploads/$workflowId': typeof AuthenticatedAdminClassifierUploadsWorkflowIdRoute
  '/admin/classifier-uploads/new': typeof AuthenticatedAdminClassifierUploadsNewRoute
  '/admin/product-drafts/$productDraftId': typeof AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren
  '/seller/classifier-batches/new': typeof AuthenticatedSellerClassifierBatchesNewRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/v1/admin/classifier-imports/$importId': typeof V1AdminClassifierImportsImportIdRouteWithChildren
  '/admin/product-drafts/$productDraftId/facts': typeof AuthenticatedAdminProductDraftsProductDraftIdFactsRoute
  '/seller/classifier-batches/$workflowId/import': typeof AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute
  '/seller/classifier-batches/$workflowId/processing': typeof AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute
  '/seller/classifier-batches/$workflowId/review': typeof AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute
  '/seller/classifier-batches/$workflowId/upload': typeof AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute
  '/v1/admin/classifier-imports/$importId/dispatch': typeof V1AdminClassifierImportsImportIdDispatchRoute
  '/v1/admin/classifier-imports/$importId/reconcile': typeof V1AdminClassifierImportsImportIdReconcileRoute
  '/v1/admin/classifier-imports/$importId/retry': typeof V1AdminClassifierImportsImportIdRetryRoute
  '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail': typeof V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/c/$category': typeof CCategoryRoute
  '/demo/kesar-textiles': typeof DemoKesarTextilesRoute
  '/demo/marketplace': typeof DemoMarketplaceRoute
  '/p/$productId': typeof PProductIdRoute
  '/s/$sellerSlug': typeof SSellerSlugRoute
  '/_authenticated/admin/classifier-imports': typeof AuthenticatedAdminClassifierImportsRoute
  '/_authenticated/admin/product-drafts': typeof AuthenticatedAdminProductDraftsRoute
  '/_authenticated/seller/classifier-batches': typeof AuthenticatedSellerClassifierBatchesRoute
  '/_authenticated/seller/leads': typeof AuthenticatedSellerLeadsRoute
  '/_authenticated/seller/products': typeof AuthenticatedSellerProductsRoute
  '/_authenticated/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/v1/admin/classifier-batches': typeof V1AdminClassifierBatchesRoute
  '/v1/admin/classifier-import-destination': typeof V1AdminClassifierImportDestinationRoute
  '/v1/admin/classifier-imports': typeof V1AdminClassifierImportsRouteWithChildren
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/admin/classifier-imports_/$importId': typeof AuthenticatedAdminClassifierImportsImportIdRoute
  '/_authenticated/admin/classifier-uploads_/$workflowId': typeof AuthenticatedAdminClassifierUploadsWorkflowIdRoute
  '/_authenticated/admin/classifier-uploads_/new': typeof AuthenticatedAdminClassifierUploadsNewRoute
  '/_authenticated/admin/product-drafts_/$productDraftId': typeof AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren
  '/_authenticated/seller/classifier-batches_/new': typeof AuthenticatedSellerClassifierBatchesNewRoute
  '/_authenticated/seller/products_/$id': typeof AuthenticatedSellerProductsIdRoute
  '/_authenticated/seller/products_/new': typeof AuthenticatedSellerProductsNewRoute
  '/v1/admin/classifier-imports/$importId': typeof V1AdminClassifierImportsImportIdRouteWithChildren
  '/_authenticated/admin/product-drafts_/$productDraftId/facts': typeof AuthenticatedAdminProductDraftsProductDraftIdFactsRoute
  '/_authenticated/seller/classifier-batches_/$workflowId/import': typeof AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute
  '/_authenticated/seller/classifier-batches_/$workflowId/processing': typeof AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute
  '/_authenticated/seller/classifier-batches_/$workflowId/review': typeof AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute
  '/_authenticated/seller/classifier-batches_/$workflowId/upload': typeof AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute
  '/v1/admin/classifier-imports/$importId/dispatch': typeof V1AdminClassifierImportsImportIdDispatchRoute
  '/v1/admin/classifier-imports/$importId/reconcile': typeof V1AdminClassifierImportsImportIdReconcileRoute
  '/v1/admin/classifier-imports/$importId/retry': typeof V1AdminClassifierImportsImportIdRetryRoute
  '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail': typeof V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/seller'
    | '/c/$category'
    | '/demo/kesar-textiles'
    | '/demo/marketplace'
    | '/p/$productId'
    | '/s/$sellerSlug'
    | '/admin/classifier-imports'
    | '/admin/product-drafts'
    | '/seller/classifier-batches'
    | '/seller/leads'
    | '/seller/products'
    | '/seller/storefront'
    | '/v1/admin/classifier-batches'
    | '/v1/admin/classifier-import-destination'
    | '/v1/admin/classifier-imports'
    | '/seller/'
    | '/admin/classifier-imports/$importId'
    | '/admin/classifier-uploads/$workflowId'
    | '/admin/classifier-uploads/new'
    | '/admin/product-drafts/$productDraftId'
    | '/seller/classifier-batches/new'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/v1/admin/classifier-imports/$importId'
    | '/admin/product-drafts/$productDraftId/facts'
    | '/seller/classifier-batches/$workflowId/import'
    | '/seller/classifier-batches/$workflowId/processing'
    | '/seller/classifier-batches/$workflowId/review'
    | '/seller/classifier-batches/$workflowId/upload'
    | '/v1/admin/classifier-imports/$importId/dispatch'
    | '/v1/admin/classifier-imports/$importId/reconcile'
    | '/v1/admin/classifier-imports/$importId/retry'
    | '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/c/$category'
    | '/demo/kesar-textiles'
    | '/demo/marketplace'
    | '/p/$productId'
    | '/s/$sellerSlug'
    | '/admin/classifier-imports'
    | '/admin/product-drafts'
    | '/seller/classifier-batches'
    | '/seller/leads'
    | '/seller/products'
    | '/seller/storefront'
    | '/v1/admin/classifier-batches'
    | '/v1/admin/classifier-import-destination'
    | '/v1/admin/classifier-imports'
    | '/seller'
    | '/admin/classifier-imports/$importId'
    | '/admin/classifier-uploads/$workflowId'
    | '/admin/classifier-uploads/new'
    | '/admin/product-drafts/$productDraftId'
    | '/seller/classifier-batches/new'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/v1/admin/classifier-imports/$importId'
    | '/admin/product-drafts/$productDraftId/facts'
    | '/seller/classifier-batches/$workflowId/import'
    | '/seller/classifier-batches/$workflowId/processing'
    | '/seller/classifier-batches/$workflowId/review'
    | '/seller/classifier-batches/$workflowId/upload'
    | '/v1/admin/classifier-imports/$importId/dispatch'
    | '/v1/admin/classifier-imports/$importId/reconcile'
    | '/v1/admin/classifier-imports/$importId/retry'
    | '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/seller'
    | '/c/$category'
    | '/demo/kesar-textiles'
    | '/demo/marketplace'
    | '/p/$productId'
    | '/s/$sellerSlug'
    | '/_authenticated/admin/classifier-imports'
    | '/_authenticated/admin/product-drafts'
    | '/_authenticated/seller/classifier-batches'
    | '/_authenticated/seller/leads'
    | '/_authenticated/seller/products'
    | '/_authenticated/seller/storefront'
    | '/v1/admin/classifier-batches'
    | '/v1/admin/classifier-import-destination'
    | '/v1/admin/classifier-imports'
    | '/_authenticated/seller/'
    | '/_authenticated/admin/classifier-imports_/$importId'
    | '/_authenticated/admin/classifier-uploads_/$workflowId'
    | '/_authenticated/admin/classifier-uploads_/new'
    | '/_authenticated/admin/product-drafts_/$productDraftId'
    | '/_authenticated/seller/classifier-batches_/new'
    | '/_authenticated/seller/products_/$id'
    | '/_authenticated/seller/products_/new'
    | '/v1/admin/classifier-imports/$importId'
    | '/_authenticated/admin/product-drafts_/$productDraftId/facts'
    | '/_authenticated/seller/classifier-batches_/$workflowId/import'
    | '/_authenticated/seller/classifier-batches_/$workflowId/processing'
    | '/_authenticated/seller/classifier-batches_/$workflowId/review'
    | '/_authenticated/seller/classifier-batches_/$workflowId/upload'
    | '/v1/admin/classifier-imports/$importId/dispatch'
    | '/v1/admin/classifier-imports/$importId/reconcile'
    | '/v1/admin/classifier-imports/$importId/retry'
    | '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CCategoryRoute: typeof CCategoryRoute
  DemoKesarTextilesRoute: typeof DemoKesarTextilesRoute
  DemoMarketplaceRoute: typeof DemoMarketplaceRoute
  PProductIdRoute: typeof PProductIdRoute
  SSellerSlugRoute: typeof SSellerSlugRoute
  V1AdminClassifierBatchesRoute: typeof V1AdminClassifierBatchesRoute
  V1AdminClassifierImportDestinationRoute: typeof V1AdminClassifierImportDestinationRoute
  V1AdminClassifierImportsRoute: typeof V1AdminClassifierImportsRouteWithChildren
  V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute: typeof V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sellerSlug': {
      id: '/s/$sellerSlug'
      path: '/s/$sellerSlug'
      fullPath: '/s/$sellerSlug'
      preLoaderRoute: typeof SSellerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$productId': {
      id: '/p/$productId'
      path: '/p/$productId'
      fullPath: '/p/$productId'
      preLoaderRoute: typeof PProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/marketplace': {
      id: '/demo/marketplace'
      path: '/demo/marketplace'
      fullPath: '/demo/marketplace'
      preLoaderRoute: typeof DemoMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/kesar-textiles': {
      id: '/demo/kesar-textiles'
      path: '/demo/kesar-textiles'
      fullPath: '/demo/kesar-textiles'
      preLoaderRoute: typeof DemoKesarTextilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/v1/admin/classifier-imports': {
      id: '/v1/admin/classifier-imports'
      path: '/v1/admin/classifier-imports'
      fullPath: '/v1/admin/classifier-imports'
      preLoaderRoute: typeof V1AdminClassifierImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/classifier-import-destination': {
      id: '/v1/admin/classifier-import-destination'
      path: '/v1/admin/classifier-import-destination'
      fullPath: '/v1/admin/classifier-import-destination'
      preLoaderRoute: typeof V1AdminClassifierImportDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/classifier-batches': {
      id: '/v1/admin/classifier-batches'
      path: '/v1/admin/classifier-batches'
      fullPath: '/v1/admin/classifier-batches'
      preLoaderRoute: typeof V1AdminClassifierBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller/storefront': {
      id: '/_authenticated/seller/storefront'
      path: '/storefront'
      fullPath: '/seller/storefront'
      preLoaderRoute: typeof AuthenticatedSellerStorefrontRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products': {
      id: '/_authenticated/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof AuthenticatedSellerProductsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/leads': {
      id: '/_authenticated/seller/leads'
      path: '/leads'
      fullPath: '/seller/leads'
      preLoaderRoute: typeof AuthenticatedSellerLeadsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/classifier-batches': {
      id: '/_authenticated/seller/classifier-batches'
      path: '/classifier-batches'
      fullPath: '/seller/classifier-batches'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/admin/product-drafts': {
      id: '/_authenticated/admin/product-drafts'
      path: '/admin/product-drafts'
      fullPath: '/admin/product-drafts'
      preLoaderRoute: typeof AuthenticatedAdminProductDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classifier-imports': {
      id: '/_authenticated/admin/classifier-imports'
      path: '/admin/classifier-imports'
      fullPath: '/admin/classifier-imports'
      preLoaderRoute: typeof AuthenticatedAdminClassifierImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/v1/admin/classifier-imports/$importId': {
      id: '/v1/admin/classifier-imports/$importId'
      path: '/$importId'
      fullPath: '/v1/admin/classifier-imports/$importId'
      preLoaderRoute: typeof V1AdminClassifierImportsImportIdRouteImport
      parentRoute: typeof V1AdminClassifierImportsRoute
    }
    '/_authenticated/seller/products_/new': {
      id: '/_authenticated/seller/products_/new'
      path: '/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof AuthenticatedSellerProductsNewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products_/$id': {
      id: '/_authenticated/seller/products_/$id'
      path: '/products/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof AuthenticatedSellerProductsIdRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/classifier-batches_/new': {
      id: '/_authenticated/seller/classifier-batches_/new'
      path: '/classifier-batches/new'
      fullPath: '/seller/classifier-batches/new'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesNewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/admin/product-drafts_/$productDraftId': {
      id: '/_authenticated/admin/product-drafts_/$productDraftId'
      path: '/admin/product-drafts/$productDraftId'
      fullPath: '/admin/product-drafts/$productDraftId'
      preLoaderRoute: typeof AuthenticatedAdminProductDraftsProductDraftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classifier-uploads_/new': {
      id: '/_authenticated/admin/classifier-uploads_/new'
      path: '/admin/classifier-uploads/new'
      fullPath: '/admin/classifier-uploads/new'
      preLoaderRoute: typeof AuthenticatedAdminClassifierUploadsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classifier-uploads_/$workflowId': {
      id: '/_authenticated/admin/classifier-uploads_/$workflowId'
      path: '/admin/classifier-uploads/$workflowId'
      fullPath: '/admin/classifier-uploads/$workflowId'
      preLoaderRoute: typeof AuthenticatedAdminClassifierUploadsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classifier-imports_/$importId': {
      id: '/_authenticated/admin/classifier-imports_/$importId'
      path: '/admin/classifier-imports/$importId'
      fullPath: '/admin/classifier-imports/$importId'
      preLoaderRoute: typeof AuthenticatedAdminClassifierImportsImportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/v1/admin/classifier-imports/$importId/retry': {
      id: '/v1/admin/classifier-imports/$importId/retry'
      path: '/retry'
      fullPath: '/v1/admin/classifier-imports/$importId/retry'
      preLoaderRoute: typeof V1AdminClassifierImportsImportIdRetryRouteImport
      parentRoute: typeof V1AdminClassifierImportsImportIdRoute
    }
    '/v1/admin/classifier-imports/$importId/reconcile': {
      id: '/v1/admin/classifier-imports/$importId/reconcile'
      path: '/reconcile'
      fullPath: '/v1/admin/classifier-imports/$importId/reconcile'
      preLoaderRoute: typeof V1AdminClassifierImportsImportIdReconcileRouteImport
      parentRoute: typeof V1AdminClassifierImportsImportIdRoute
    }
    '/v1/admin/classifier-imports/$importId/dispatch': {
      id: '/v1/admin/classifier-imports/$importId/dispatch'
      path: '/dispatch'
      fullPath: '/v1/admin/classifier-imports/$importId/dispatch'
      preLoaderRoute: typeof V1AdminClassifierImportsImportIdDispatchRouteImport
      parentRoute: typeof V1AdminClassifierImportsImportIdRoute
    }
    '/_authenticated/seller/classifier-batches_/$workflowId/upload': {
      id: '/_authenticated/seller/classifier-batches_/$workflowId/upload'
      path: '/classifier-batches/$workflowId/upload'
      fullPath: '/seller/classifier-batches/$workflowId/upload'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdUploadRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/classifier-batches_/$workflowId/review': {
      id: '/_authenticated/seller/classifier-batches_/$workflowId/review'
      path: '/classifier-batches/$workflowId/review'
      fullPath: '/seller/classifier-batches/$workflowId/review'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdReviewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/classifier-batches_/$workflowId/processing': {
      id: '/_authenticated/seller/classifier-batches_/$workflowId/processing'
      path: '/classifier-batches/$workflowId/processing'
      fullPath: '/seller/classifier-batches/$workflowId/processing'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/classifier-batches_/$workflowId/import': {
      id: '/_authenticated/seller/classifier-batches_/$workflowId/import'
      path: '/classifier-batches/$workflowId/import'
      fullPath: '/seller/classifier-batches/$workflowId/import'
      preLoaderRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdImportRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/admin/product-drafts_/$productDraftId/facts': {
      id: '/_authenticated/admin/product-drafts_/$productDraftId/facts'
      path: '/facts'
      fullPath: '/admin/product-drafts/$productDraftId/facts'
      preLoaderRoute: typeof AuthenticatedAdminProductDraftsProductDraftIdFactsRouteImport
      parentRoute: typeof AuthenticatedAdminProductDraftsProductDraftIdRoute
    }
    '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail': {
      id: '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
      path: '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
      fullPath: '/v1/seller/classifier-batches/$workflowId/images/$imageId/thumbnail'
      preLoaderRoute: typeof V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerClassifierBatchesRoute: typeof AuthenticatedSellerClassifierBatchesRoute
  AuthenticatedSellerLeadsRoute: typeof AuthenticatedSellerLeadsRoute
  AuthenticatedSellerProductsRoute: typeof AuthenticatedSellerProductsRoute
  AuthenticatedSellerStorefrontRoute: typeof AuthenticatedSellerStorefrontRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
  AuthenticatedSellerClassifierBatchesNewRoute: typeof AuthenticatedSellerClassifierBatchesNewRoute
  AuthenticatedSellerProductsIdRoute: typeof AuthenticatedSellerProductsIdRoute
  AuthenticatedSellerProductsNewRoute: typeof AuthenticatedSellerProductsNewRoute
  AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute
  AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute
  AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute
  AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute: typeof AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerClassifierBatchesRoute:
    AuthenticatedSellerClassifierBatchesRoute,
  AuthenticatedSellerLeadsRoute: AuthenticatedSellerLeadsRoute,
  AuthenticatedSellerProductsRoute: AuthenticatedSellerProductsRoute,
  AuthenticatedSellerStorefrontRoute: AuthenticatedSellerStorefrontRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
  AuthenticatedSellerClassifierBatchesNewRoute:
    AuthenticatedSellerClassifierBatchesNewRoute,
  AuthenticatedSellerProductsIdRoute: AuthenticatedSellerProductsIdRoute,
  AuthenticatedSellerProductsNewRoute: AuthenticatedSellerProductsNewRoute,
  AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute:
    AuthenticatedSellerClassifierBatchesWorkflowIdImportRoute,
  AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute:
    AuthenticatedSellerClassifierBatchesWorkflowIdProcessingRoute,
  AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute:
    AuthenticatedSellerClassifierBatchesWorkflowIdReviewRoute,
  AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute:
    AuthenticatedSellerClassifierBatchesWorkflowIdUploadRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedAdminProductDraftsProductDraftIdRouteChildren {
  AuthenticatedAdminProductDraftsProductDraftIdFactsRoute: typeof AuthenticatedAdminProductDraftsProductDraftIdFactsRoute
}

const AuthenticatedAdminProductDraftsProductDraftIdRouteChildren: AuthenticatedAdminProductDraftsProductDraftIdRouteChildren =
  {
    AuthenticatedAdminProductDraftsProductDraftIdFactsRoute:
      AuthenticatedAdminProductDraftsProductDraftIdFactsRoute,
  }

const AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren =
  AuthenticatedAdminProductDraftsProductDraftIdRoute._addFileChildren(
    AuthenticatedAdminProductDraftsProductDraftIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedAdminClassifierImportsRoute: typeof AuthenticatedAdminClassifierImportsRoute
  AuthenticatedAdminProductDraftsRoute: typeof AuthenticatedAdminProductDraftsRoute
  AuthenticatedAdminClassifierImportsImportIdRoute: typeof AuthenticatedAdminClassifierImportsImportIdRoute
  AuthenticatedAdminClassifierUploadsWorkflowIdRoute: typeof AuthenticatedAdminClassifierUploadsWorkflowIdRoute
  AuthenticatedAdminClassifierUploadsNewRoute: typeof AuthenticatedAdminClassifierUploadsNewRoute
  AuthenticatedAdminProductDraftsProductDraftIdRoute: typeof AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedAdminClassifierImportsRoute:
    AuthenticatedAdminClassifierImportsRoute,
  AuthenticatedAdminProductDraftsRoute: AuthenticatedAdminProductDraftsRoute,
  AuthenticatedAdminClassifierImportsImportIdRoute:
    AuthenticatedAdminClassifierImportsImportIdRoute,
  AuthenticatedAdminClassifierUploadsWorkflowIdRoute:
    AuthenticatedAdminClassifierUploadsWorkflowIdRoute,
  AuthenticatedAdminClassifierUploadsNewRoute:
    AuthenticatedAdminClassifierUploadsNewRoute,
  AuthenticatedAdminProductDraftsProductDraftIdRoute:
    AuthenticatedAdminProductDraftsProductDraftIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface V1AdminClassifierImportsImportIdRouteChildren {
  V1AdminClassifierImportsImportIdDispatchRoute: typeof V1AdminClassifierImportsImportIdDispatchRoute
  V1AdminClassifierImportsImportIdReconcileRoute: typeof V1AdminClassifierImportsImportIdReconcileRoute
  V1AdminClassifierImportsImportIdRetryRoute: typeof V1AdminClassifierImportsImportIdRetryRoute
}

const V1AdminClassifierImportsImportIdRouteChildren: V1AdminClassifierImportsImportIdRouteChildren =
  {
    V1AdminClassifierImportsImportIdDispatchRoute:
      V1AdminClassifierImportsImportIdDispatchRoute,
    V1AdminClassifierImportsImportIdReconcileRoute:
      V1AdminClassifierImportsImportIdReconcileRoute,
    V1AdminClassifierImportsImportIdRetryRoute:
      V1AdminClassifierImportsImportIdRetryRoute,
  }

const V1AdminClassifierImportsImportIdRouteWithChildren =
  V1AdminClassifierImportsImportIdRoute._addFileChildren(
    V1AdminClassifierImportsImportIdRouteChildren,
  )

interface V1AdminClassifierImportsRouteChildren {
  V1AdminClassifierImportsImportIdRoute: typeof V1AdminClassifierImportsImportIdRouteWithChildren
}

const V1AdminClassifierImportsRouteChildren: V1AdminClassifierImportsRouteChildren =
  {
    V1AdminClassifierImportsImportIdRoute:
      V1AdminClassifierImportsImportIdRouteWithChildren,
  }

const V1AdminClassifierImportsRouteWithChildren =
  V1AdminClassifierImportsRoute._addFileChildren(
    V1AdminClassifierImportsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CCategoryRoute: CCategoryRoute,
  DemoKesarTextilesRoute: DemoKesarTextilesRoute,
  DemoMarketplaceRoute: DemoMarketplaceRoute,
  PProductIdRoute: PProductIdRoute,
  SSellerSlugRoute: SSellerSlugRoute,
  V1AdminClassifierBatchesRoute: V1AdminClassifierBatchesRoute,
  V1AdminClassifierImportDestinationRoute:
    V1AdminClassifierImportDestinationRoute,
  V1AdminClassifierImportsRoute: V1AdminClassifierImportsRouteWithChildren,
  V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute:
    V1SellerClassifierBatchesWorkflowIdImagesImageIdThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
